import { NextResponse } from "next/server";

import { Event } from "@/database/event.model";
import { connectToDatabase } from "@/lib/mongodb";

type EventRouteContext = {
  params: Promise<{ slug: string }>;
};

const slugPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

export async function GET(_request: Request, { params }: EventRouteContext) {
  const { slug } = await params;
  const normalizedSlug = slug.trim().toLowerCase();

  // Match the URL-safe slug format generated by the Event model.
  if (!normalizedSlug || !slugPattern.test(normalizedSlug)) {
    return NextResponse.json(
      { message: "A valid event slug is required." },
      { status: 400 },
    );
  }

  try {
    await connectToDatabase();

    const event = await Event.findOne({ slug: normalizedSlug }).lean();

    if (!event) {
      return NextResponse.json({ message: "Event not found." }, { status: 404 });
    }

    return NextResponse.json({ event }, { status: 200 });
  } catch (error) {
    console.error("Failed to fetch event by slug:", error);
    return NextResponse.json(
      { message: "Unable to fetch the event." },
      { status: 500 },
    );
  }
}
