export const events = [
  {
    title: "GitHub Connect Melbourne 2026",
    image: "/images/event1.png",
    slug: "github-connect-melbourne-2026",
    location: "Melbourne, Australia",
    date: "September 3, 2026",
    time: "8:30 AM AEST",
  },
  {
    title: "GitHub Connect Auckland 2026",
    image: "/images/event2.png",
    slug: "github-connect-auckland-2026",
    location: "Auckland, New Zealand",
    date: "September 8, 2026",
    time: "8:30 AM NZST",
  },
  {
    title: "GitHub Universe 2026",
    image: "/images/event3.png",
    slug: "github-universe-2026",
    location: "Fort Mason Center, San Francisco & online",
    date: "October 28–29, 2026",
    time: "9:00 AM PDT",
  },
  {
    title: "DevFest 2026",
    image: "/images/event4.png",
    slug: "devfest-2026",
    location: "Developer communities worldwide",
    date: "October 1–December 31, 2026",
    time: "Times vary by city",
  },
  {
    title: "Hacktoberfest 2026",
    image: "/images/event5.png",
    slug: "hacktoberfest-2026",
    location: "In person & online worldwide",
    date: "October 1–31, 2026",
    time: "All day",
  },
  {
    title: "Devcon 8",
    image: "/images/event6.png",
    slug: "devcon-8",
    location: "Mumbai, India",
    date: "November 3–6, 2026",
    time: "9:00 AM IST",
  },
];
